version: '3.9'
services:
  dataset:
    build: .
    environment:
      - GIN_MODE=release
      - BNB_PORT=8080
      - BNB-PROJECT-ID=mr-bonobo
      - BNB-NAME=mr-bonobo-dev
      - BNB-FIREBASE-CONFIG=./secret/config-firebase.json
      - BNB-FIREBASE-CREDENTIALS=./secret/credentials-firebase.json
      - GOOGLE_APPLICATION_CREDENTIALS=./secret/credentials-firebase.json
    ports:
      - '8080:8080'
    
