version: '3.9'
services:
  dataset:
    build: .
    environment:
      - GIN_MODE=release
      - BNB_PORT=8080
      - BNB_NAME={LOGS_NAME}
      - BNB_PROJECT_ID={FIREBASE_PROJECT_ID}
      - BNB_DATABASE_URL=https://{PROJECT_ID}.firebaseio.com
      - BNB_STORAGE_URL={PROJECT_ID}.appspot.com
      - GOOGLE_APPLICATION_CREDENTIALS=./secret/credentials-firebase.json
    ports:
      - '8080:8080'
    
