version: "3.9"
   
services:
  postgres:
    image: postgres
    volumes:
      - ~/db/posgtgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: 
      - "5432:5432"
  mongodb:
    image : mongo
    container_name: ${MONGO_CONTAINER}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    volumes:
    - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    - ~/db/mongo:/data/db
    ports:
    - "${MONGO_PORT}:27017"
    restart: unless-stopped