version: '3.9'
services:
  dataset:
    image: {{ IMAGE_NAME }}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GIN_MODE=release
      - BNB_PORT=8080
      - BNB_NAME={{ NAME }}
      - BNB_PROJECT_ID={ PROJECT_ID }
      - BNB_DATABASE_URL={{ DATABASE_URL }}
      - BNB_STORAGE_URL={{ STORAGE_URL }}
      - GOOGLE_APPLICATION_CREDENTIALS={{ CREDENTIALS_PATH }}
    ports:
      - '8080:8080'
    
